"""ai pipeline and student comment

Revision ID: 973f811557bc
Revises: e06a72f62c70
Create Date: 2026-09-24 22:04:05.348142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '973f811557bc'
down_revision: Union[str, Sequence[str], None] = 'e06a72f62c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_redactions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('rects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('auto', 'manual')", name='ck_submission_redactions_source'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assignments', sa.Column('guideline_path', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('guideline_filename', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('pipeline_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('submission_annotations', sa.Column('source', sa.String(), server_default='ta', nullable=False))
    op.add_column('submission_annotations', sa.Column('status', sa.String(), server_default='published', nullable=False))
    op.alter_column('submission_annotations', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('submission_documents', sa.Column('anonymized_pdf_path', sa.String(), nullable=True))
    op.add_column('submission_documents', sa.Column('page_texts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submissions', sa.Column('student_comment', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('pipeline_status', sa.String(), server_default='not_started', nullable=False))
    op.add_column('submissions', sa.Column('pipeline_step', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('pipeline_error', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('difficulty_reason', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('assigned_ta_id', sa.Uuid(), nullable=True))
    op.add_column('submissions', sa.Column('needs_anonymization_check', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key('submissions_assigned_ta_id_fkey', 'submissions', 'users', ['assigned_ta_id'], ['id'])
    # Check constraints on existing tables aren't autogenerated.
    op.create_check_constraint(
        'ck_submissions_pipeline_status', 'submissions',
        "pipeline_status IN ('not_started', 'queued', 'processing', 'done', 'failed')",
    )
    op.create_check_constraint('ck_submissions_difficulty_range', 'submissions', 'difficulty >= 1 AND difficulty <= 100')
    op.create_check_constraint('ck_submission_annotations_source', 'submission_annotations', "source IN ('ta', 'ai')")
    op.create_check_constraint(
        'ck_submission_annotations_status', 'submission_annotations',
        "status IN ('published', 'suggested', 'dismissed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_submission_annotations_status', 'submission_annotations', type_='check')
    op.drop_constraint('ck_submission_annotations_source', 'submission_annotations', type_='check')
    op.drop_constraint('ck_submissions_difficulty_range', 'submissions', type_='check')
    op.drop_constraint('ck_submissions_pipeline_status', 'submissions', type_='check')
    op.drop_constraint('submissions_assigned_ta_id_fkey', 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'needs_anonymization_check')
    op.drop_column('submissions', 'assigned_ta_id')
    op.drop_column('submissions', 'ai_summary')
    op.drop_column('submissions', 'difficulty_reason')
    op.drop_column('submissions', 'difficulty')
    op.drop_column('submissions', 'pipeline_error')
    op.drop_column('submissions', 'pipeline_step')
    op.drop_column('submissions', 'pipeline_status')
    op.drop_column('submissions', 'student_comment')
    op.drop_column('submission_documents', 'page_texts')
    op.drop_column('submission_documents', 'anonymized_pdf_path')
    # Unaccepted AI suggestions have no author and can't survive NOT NULL.
    op.execute("DELETE FROM submission_annotations WHERE author_id IS NULL")
    op.alter_column('submission_annotations', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('submission_annotations', 'status')
    op.drop_column('submission_annotations', 'source')
    op.drop_column('assignments', 'pipeline_started_at')
    op.drop_column('assignments', 'guideline_filename')
    op.drop_column('assignments', 'guideline_path')
    op.drop_table('submission_redactions')
    # ### end Alembic commands ###
